# Generated by Django 5.2.3 on 2025-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimage",
            name="image",
        ),
        migrations.AddField(
            model_name="itemimage",
            name="azure_file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
